// Central place for the shapes of data used across the app.
// Keeping these in one file means the form, table, filters, and Supabase
// calls all agree on what an "asset" looks like.

export const DEVICE_TYPES = [
  "Laptop",
  "Desktop",
  "Monitor",
  "Phone",
  "Tablet",
  "Printer",
  "Peripheral",
  "Other",
] as const;

export type DeviceType = (typeof DEVICE_TYPES)[number];

export const ASSET_STATUSES = [
  "Active",
  "Available",
  "In Repair",
  "Retired",
  "Lost",
] as const;

export type AssetStatus = (typeof ASSET_STATUSES)[number];

// Matches the `assets` table in supabase/schema.sql
export interface Asset {
  id: string;
  asset_tag: string;
  device_type: DeviceType;
  brand: string | null;
  model: string | null;
  serial_number: string | null;
  assigned_to: string | null;
  location: string | null;
  purchase_date: string | null; // ISO date string, e.g. "2025-03-14"
  warranty_expiry: string | null; // ISO date string
  status: AssetStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

// The fields a user actually fills in on the form.
// (id/created_at/updated_at are generated by the database.)
export type AssetInput = Omit<Asset, "id" | "created_at" | "updated_at">;
